# Basic
title: å†‰æ°æ–‡
subtitle: ä¸ªäººç«™
description: ç»ˆäºç­‰åˆ°ä½ ï¼Œè¿˜å¥½æ²¡æ”¾å¼ƒï¼ä¸€ç›´åœ¨æ¨¡ä»¿....
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ranjiewen
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: å›¾åƒå¤„ç† / æœºå™¨å­¦ä¹ 
url: "http://ranjiewwen.github.io"

# Comment
comment:
    # disqus: lilian
    duoshuo: ranjiewen 

# Social
social:
    weibo: 15623216060
    github: ranjiewwen
    #gsite: liliandreamworld
    cnblogs: ranjiewen
    # twitter: 
    mail: jiewenaran@gmail.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: e572ae9801b3a18891f123796b889f77

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-88738012-1   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/ranjiewwen/ranjiewwen.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /blog/:year/:month/:title.html 

markdown: kramdown


kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge


# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: 

# The blog button should not be removed.
blog_button:
    title: home

# Navigation buttons in the front page.s
nav:
    - {title: paper, description: archive, url: '/archive'}   
    - {title: tags, description: tags, url: '/tags'}
    - {title: messages, description: messages, url: '/messages'}
    - {title: links, description: links, url: '/links'}      
    - {title: about, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
